Repository ContentSquare/chproxy, pull requests merged in 2022-10, with the labels that each got.

#238 Move from github.com/DataDog/zstd to github.com/klauspost/compress/zstd
  chdecompressor/decompressor.go
  go.mod
  go.sum
Labels: size/XS

#240 consolidate builds
  .goreleaser.yml
Labels: size/M

#247 fix: docker image build arm64/v8
  .goreleaser.yml
Labels: size/XS

#246 add new template
  .github/ISSUE_TEMPLATE/question.md
Labels: size/S

#251 chore: add ignore tags for release action
  .github/workflows/release.yml
Labels: size/XS

#252 fix: add v prefix for docker images
  .goreleaser.yml
Labels: size/S

#250 make wildcarded feature work on more patterns
  config/README.md
  config/config.go
  config/config_test.go
  docs/content/en/configuration/users.md
  proxy.go
  proxy_test.go
  scope.go
  utils.go
Labels: size/L

#225 Fix: Add support for running CHProxy behind another proxy
  config/config.go
  config/config_test.go
  config/testdata/bad.proxy_settings.yml
  config/testdata/full.yml
  config/types.go
  docs/content/en/configuration/default.md
  docs/content/en/configuration/proxy.md
  main.go
  main_test.go
  proxy_handler.go
  proxy_handler_test.go
  testdata/https.proxy-enabled.yml
Labels: size/L

#253 add changelog
  CHANGELOG.md
  docs/content/en/changelog.md
  docs/content/en/faq.md
Labels: size/M

#242 Feat/query retry
  config/README.md
  config/config.go
  docs/content/en/configuration/metrics.md
  io.go
  metrics.go
  proxy.go
  proxyretry_test.go
  scope.go
Labels: size/L, wip
