Repository ContentSquare/chproxy, pull requests merged in 2022-04, with the labels that each got.

#153 fix: fix the bytes encode/decode for redis cache
  .gitignore
  cache/redis_cache.go
  main_test.go
  proxy_test.go
Labels: size/M

#159 Remove reference to Read the docs (deprecated)
  docs/content/cn/index.md
  docs/content/en/configuration/security.md
  docs/content/en/faq.md
  docs/content/en/history.md
  docs/content/en/use-cases/authorize-users.md
  docs/content/en/use-cases/spread-insert.md
  docs/content/en/use-cases/spread-select.md
  scope.go
Labels: size/S

#152 increase code coverage
  cache/async_cache.go
  cache/async_cache_test.go
  cache/filesystem_cache_test.go
  cache/redis_cache_test.go
  cache/transaction_registry_redis.go
  cache/transaction_registry_redis_test.go
  config/config_test.go
  go.mod
  go.sum
Labels: size/XL

#158 chore: Add more linters and fix go code
  .golangci.yml
  cache/async_cache.go
  cache/filesystem_cache.go
  cache/redis_cache.go
  cache/transaction_registry_inmem.go
  cache/transaction_registry_redis.go
  cache/utils.go
  chdecompressor/decompressor.go
  clients/redis.go
  config/config.go
  config/types.go
  config/utils.go
  heartbeat.go
  io.go
  log/log.go
  main.go
  main_test.go
  metrics.go
  proxy.go
  scope.go
  utils.go
Labels: size/L

#161 chore: install.md - docker usage
  docs/content/en/install.md
Labels: size/S

#146 Improve handling of concurrent identical queries
  cache/async_cache.go
  cache/async_cache_test.go
  cache/filesystem_cache.go
  cache/redis_cache.go
  cache/transaction_registry.go
  cache/transaction_registry_inmem.go
  cache/transaction_registry_redis.go
  cache/transaction_registry_redis_test.go
  cache/transaction_registry_test.go
  config/README.md
  config/config.go
  config/config_test.go
  docs/content/en/configuration/default.md
  go.mod
  go.sum
  main.go
  main_test.go
  proxy.go
  proxy_test.go
  testdata/http.concurrent.transaction.yml
Labels: size/XL

#165 option: fix set sessionTimeout invalid
  utils.go
  utils_test.go
Labels: size/M
