Repository ContentSquare/chproxy, pull requests merged in 2022-07, with the labels that each got.

#179 Create feature issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/S

#178 Create bug issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/S

#184 Fix redis transaction registry
  cache/transaction_registry_redis.go
  proxy_test.go
Labels: size/XS

#189 fix(newParamsRegistry): inistialisation bug
  proxy_test.go
  scope.go
Labels: size/XS

#192 fix(proxy): return error message when query fails
  cache/async_cache.go
  io.go
  main_test.go
  proxy.go
Labels: size/S

#195 set default max_execution_time to 120s
  config/config.go
  config/config_test.go
  config/testdata/full.yml
  docs/content/cn/index.md
  docs/content/en/configuration/default.md
  proxy_test.go
Labels: size/M
