Repository ContentSquare/chproxy, pull requests merged in 2022-08, with the labels that each got.

#200 refactor: use os and io packages to replace some ioutils functions
  cache/filesystem_cache.go
  chdecompressor/decompressor_test.go
  config/config.go
  heartbeat.go
  io_test.go
  log/log.go
  main_test.go
  proxy_test.go
  scope.go
  utils.go
Labels: size/M

#202 update golangci-lint version + gofmt
  .github/workflows/golangci-lint.yaml
  config/config.go
  utils_test.go
Labels: size/S

#190 fix(asyncCache): propagation of maxExecutionTime
  proxy.go
Labels: size/S

#205 build docker image for arm64
  .goreleaser.yml
Labels: size/XS

#207 Chore/docker build push arm64
  .goreleaser.yml
  Dockerfile
Labels: size/XS

#208 fix: docker image for arm64
  .goreleaser.yml
Labels: size/XS

#203 improve proxy unit tests
  proxy_test.go
Labels: size/M

#213 [docs] Update chproxy documentation design
  docs/README.md
  docs/assets/css/main.css
  docs/nuxt.config.js
  docs/package.json
  docs/static/favicon.svg
  docs/static/images/logo-white.svg
  docs/yarn.lock
Labels: size/L

#212 Fix memory issue & improve processing speed
  cache/buffered_response_writer.go
  cache/cache.go
  cache/filesystem_cache.go
  cache/filesystem_cache_test.go
  cache/key.go
  cache/redis_cache.go
  cache/redis_cache_test.go
  cache/tmp_file_response_writer.go
  cache/tmp_file_response_writer_test.go
  main_test.go
  proxy.go
Labels: size/XXL

#214 feat(healthcheck): rely on /ping for healthcheck
  config/README.md
  config/config.go
  config/config_test.go
  config/testdata/bad.heartbeat_interval.duplicate.yml
  config/testdata/bad.heartbeat_section.empty.yml
  config/testdata/bad.heartbeat_section.empty2.yml
  config/testdata/full.yml
  docs/content/cn/index.md
  docs/content/en/configuration/default.md
  heartbeat.go
  heartbeat_test.go
  proxy_test.go
Labels: size/L

#215 Update doc
  config/README.md
  docs/content/cn/index.md
  docs/content/en/configuration/default.md
Labels: size/XS
